apiVersion: v1
kind: Secret
metadata:
  name: cb-example-auth-bryan2
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg==  # Administrator
  password: cGFzc3dvcmQ=          # password
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: default2
spec:
  memoryQuota: 128Mi
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example-bryan2
spec:
  securityContext:
    fsGroup: 1000590000
  image: couchbase/server:6.6.0
  security:
    adminSecret: cb-example-auth-bryan2
  networking:
    exposeAdminConsole: true
    adminConsoleServices:
    - data
  buckets:
    managed: true
  servers:
  - size: 1
    name: all_services
    services:
    - data
    - index
    - query
    - search
    - eventing
    - analytics
    volumeMounts:
      default: couchbase
   #   data:  couchbase
  volumeClaimTemplates:
    - metadata:
        name: couchbase
        annotations:
          trident.netapp.io/cloneFromPVC: cb-example-bryan-0000-default-01
      spec:
        storageClassName: "basicnetappiscsi"
        resources:
          requests:
            storage: 10Gi
